/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     2017/3/10 22:30:08                           */
/*==============================================================*/

DROP DATABASE IF EXISTS LMS;

CREATE DATABASE LMS;

USE LMS;

DROP TABLE IF EXISTS CAR;

DROP TABLE IF EXISTS CARSTATE;

DROP TABLE IF EXISTS CARTYPE;

DROP TABLE IF EXISTS CITY;

DROP TABLE IF EXISTS DELIVERYSPOT;

DROP TABLE IF EXISTS EMPLOYEE;

DROP TABLE IF EXISTS LINE;

DROP TABLE IF EXISTS LINEDETAILE;

DROP TABLE IF EXISTS ODER;

DROP TABLE IF EXISTS ORDERSTATE;

DROP TABLE IF EXISTS POSITION;

DROP TABLE IF EXISTS POWER;

DROP TABLE IF EXISTS PROVINCE;

DROP TABLE IF EXISTS RECEIPT;

DROP TABLE IF EXISTS RECEIPTDETAILE;

DROP TABLE IF EXISTS `USE`;

/*==============================================================*/
/* Table: CAR                                                   */
/*==============================================================*/
CREATE TABLE CAR
(
   CARID                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   CARNO                VARCHAR(20),
   WORKNO               VARCHAR(20),
   CARTYPEID            INT,
   CARSIZE              INT,
   TONNAGE              INT,
   BUYTIME              DATE,
   LEAVETIME            DATE,
   CARSTATEID           INT,
   LINEID               INT,
   EMPID                INT,
   REMARK               VARCHAR(500),
   PRIMARY KEY (CARID)
);

/*==============================================================*/
/* Table: CARSTATE                                              */
/*==============================================================*/
CREATE TABLE CARSTATE
(
   CARSTATEID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(20),
   PRIMARY KEY (CARSTATEID)
);

/*==============================================================*/
/* Table: CARTYPE                                               */
/*==============================================================*/
CREATE TABLE CARTYPE
(
   CARTYPEID            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(20),
   PRIMARY KEY (CARTYPEID)
);

/*==============================================================*/
/* Table: CITY                                                  */
/*==============================================================*/
CREATE TABLE CITY
(
   CITYID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(20),
   ZIPCODE				VARCHAR(10),
   PROVINCEID           INT,
   PRIMARY KEY (CITYID)
);

/*==============================================================*/
/* Table: DELIVERYSPOT                                          */
/*==============================================================*/
CREATE TABLE DELIVERYSPOT
(
   DELIVERYSPOTID       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   DELIVERYSPOTNO       VARCHAR(20),
   NAME                 VARCHAR(20),
   PROVINCEID           INT,
   CITYID               INT,
   EMPID                INT,
   TEL                  VARCHAR(20),
   STARTSCOPE           DECIMAL(9,2),
   STARTPRICE           DECIMAL(9,2),
   SECONDPRICE          DECIMAL(9,2),
   STARTVOLUMESCOPE     DECIMAL(9,2),
   STARTVOLUMEPRICE     DECIMAL(9,2),
   SECONDVOLUMEPRICE    DECIMAL(9,2),
   FLAG					INT,
   PRIMARY KEY (DELIVERYSPOTID)
);

/*==============================================================*/
/* Table: EMPLOYEE                                              */
/*==============================================================*/
CREATE TABLE EMPLOYEE
(
   EMPID                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   EMPNO                VARCHAR(20),
   NAME                 VARCHAR(20),
   GENDER               INT,
   BIRTHDAY             DATE,
   ADDRESS              VARCHAR(100),
   TEL                  VARCHAR(20),
   STARTWORDTIME        DATE,
   SALARY               DECIMAL(9,2),
   EMAIL                VARCHAR(50),
   CARDID               VARCHAR(20),
   POSITIONID           INT,
   DELIVERYSPOTID       INT,
   FLAG                 INT,
   PRIMARY KEY (EMPID)
);

/*==============================================================*/
/* Table: LINE                                                  */
/*==============================================================*/
CREATE TABLE LINE
(
   LINEID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   LINENO               INT,
   LINENAME             VARCHAR(20),
   LENGTH               INT,
   PRIMARY KEY (LINEID)
);

/*==============================================================*/
/* Table: LINEDETAILE                                           */
/*==============================================================*/
CREATE TABLE LINEDETAILE
(
   LINEDETAILEID        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   LINEID               INT,
   DELIVERYSPOTID       INT,
   LINEINDEX            INT,
   PRIMARY KEY (LINEDETAILEID)
);

/*==============================================================*/
/* Table: ODER                                                  */
/*==============================================================*/
CREATE TABLE ODER
(
   ORDERID              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   ORDERNO              VARCHAR(50),
   SENDNAME             VARCHAR(20),
   SENDADDRESS          VARCHAR(100),
   SENDTEL              VARCHAR(20),
   SENDMOBILE           VARCHAR(20),
   SENDPOSTCODE         VARCHAR(20),
   RECEIVENAME          VARCHAR(20),
   RECEIVEADDRESS       VARCHAR(100),
   RECEIVETEL           VARCHAR(20),
   RECEIVEMOBILE        VARCHAR(20),
   RECEIVEPOSTCODE      VARCHAR(20),
   ORDERSTATEID         INT,
   TOTALPRICE           DECIMAL(9,2),
   INSUREPRICE          DECIMAL(9,2),
   GOODSPRICE           DECIMAL(9,2),
   VOLUME               DECIMAL(9,2),
   WEIGHT               DECIMAL(9,2),
   REMARK               VARCHAR(500),
   CREATETIME           DATE,
   DELIVERYSPOTID       INT,
   PRIMARY KEY (ORDERID)
);

/*==============================================================*/
/* Table: ORDERSTATE                                            */
/*==============================================================*/
CREATE TABLE ORDERSTATE
(
   ORDERSTATEID         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   `NAME`                 VARCHAR(20),
   PRIMARY KEY (ORDERSTATEID)
);

/*==============================================================*/
/* Table: POSITION                                              */
/*==============================================================*/
CREATE TABLE `POSITION`
(
   `POSITIONID`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   `NAME`                 VARCHAR(20),
   PRIMARY KEY (`POSITIONID`)
);

/*==============================================================*/
/* Table: POWER                                                 */
/*==============================================================*/
CREATE TABLE POWER
(
   POWERID              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(20),
   PRIMARY KEY (POWERID)
);

/*==============================================================*/
/* Table: PROVINCE                                              */
/*==============================================================*/
CREATE TABLE PROVINCE
(
   PROVINCEID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   NAME                 VARCHAR(20),
   PRIMARY KEY (PROVINCEID)
);

/*==============================================================*/
/* Table: RECEIPT                                               */
/*==============================================================*/
CREATE TABLE RECEIPT
(
   RECEIPTID            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   CARNO                VARCHAR(20),
   DELIVERYSPOTID       INT,
   EMP_EMPID            INT,
   FROMNAME             VARCHAR(20),
   TONAME               VARCHAR(20),
   CREATETIME           VARCHAR(20),
   REMARK               VARCHAR(500),
   FLAG                 INT,
   EMPID                INT,
   RECEIPTNO            VARCHAR(30),
   RTYPE                VARCHAR(20),
   PRIMARY KEY (RECEIPTID)
);

/*==============================================================*/
/* Table: RECEIPTDETAILE                                        */
/*==============================================================*/
CREATE TABLE RECEIPTDETAILE
(
   RDID                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   RECEIPTID            INT,
   ORDERID              INT,
   PRIMARY KEY (RDID)
);

/*==============================================================*/
/* Table: `USE`                                                 */
/*==============================================================*/
CREATE TABLE `USE`
(
   USERID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   USERNAME             VARCHAR(20),
   PASSOWRD             VARCHAR(20),
   POWERID              INT,
   DELIVERYSPOTID       INT,
   EMPID                INT,
   PRIMARY KEY (USERID)
);



INSERT INTO power (POWERID,NAME) VALUES 
(1,'超级管理员')
,(2,'配送点管理员')
,(3,'配送点操作员')
;

INSERT INTO `use` (USERID,USERNAME,PASSOWRD,POWERID,DELIVERYSPOTID,EMPID) VALUES 
(1,'admin','admin',1,NULL,NULL)
;


ALTER TABLE province AUTO_INCREMENT = 6;

INSERT INTO province (`NAME`)
VALUES  ('辽宁省');
INSERT INTO province (`NAME`)
VALUES  ('吉林省');
INSERT INTO province (`NAME`)
VALUES  ('黑龙江省');
INSERT INTO province (`NAME`)
VALUES  ('上海市');
INSERT INTO province (`NAME`)
VALUES  ('江苏省');
INSERT INTO province (`NAME`)
VALUES  ('浙江省');
INSERT INTO province (`NAME`)
VALUES  ('安徽省');
INSERT INTO province (`NAME`)
VALUES  ('福建省');
INSERT INTO province (`NAME`)
VALUES  ('江西省');
INSERT INTO province (`NAME`)
VALUES  ('山东省');
INSERT INTO province (`NAME`)
VALUES  ('河南省');
INSERT INTO province (`NAME`)
VALUES  ('湖北省');
INSERT INTO province (`NAME`)
VALUES  ('湖南省');




INSERT INTO province (`NAME`)
VALUES  ('广东省');
INSERT INTO province (`NAME`)
VALUES  ('广西壮族自治区');
INSERT INTO province (`NAME`)
VALUES  ('海南省');
INSERT INTO province (`NAME`)
VALUES  ('重庆市');
INSERT INTO province (`NAME`)
VALUES  ('四川省');
INSERT INTO province (`NAME`)
VALUES  ('贵州省');
INSERT INTO province (`NAME`)
VALUES  ('云南省');
INSERT INTO province (`NAME`)
VALUES  ('西藏自治区');
INSERT INTO province (`NAME`)
VALUES  ('陕西省');
INSERT INTO province (`NAME`)
VALUES  ('甘肃省');
INSERT INTO province (`NAME`)
VALUES  ('青海省');
INSERT INTO province (`NAME`)
VALUES  ('宁夏回族自治区');
INSERT INTO province (`NAME`)
VALUES  ('新疆维吾尔自治区');
INSERT INTO province (`NAME`)
VALUES  ('香港特别行政区');
INSERT INTO province (`NAME`)
VALUES  ('澳门特别行政区');
INSERT INTO province (`NAME`)
VALUES  ('台湾省');














INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('北京市', '100000', 1);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('天津市', '100000', 2);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('石家庄市', '050000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('唐山市', '063000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('秦皇岛市', '066000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('邯郸市', '056000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('邢台市', '054000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('保定市', '071000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('张家口市', '075000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('承德市', '067000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('沧州市', '061000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('廊坊市', '065000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('衡水市', '053000', 3);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('太原市', '030000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('大同市', '037000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阳泉市', '045000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('长治市', '046000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('晋城市', '048000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('朔州市', '036000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('晋中市', '030600', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('运城市', '044000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('忻州市', '034000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('临汾市', '041000', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('吕梁市', '030500', 4);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('呼和浩特市', '010000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('包头市', '014000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('乌海市', '016000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('赤峰市', '024000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('通辽市', '028000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鄂尔多斯市', '010300', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('呼伦贝尔市', '021000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('巴彦淖尔市', '014400', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('乌兰察布市', '011800', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('兴安盟', '137500', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('锡林郭勒盟', '011100', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阿拉善盟', '016000', 5);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('沈阳市', '110000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('大连市', '116000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鞍山市', '114000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('抚顺市', '113000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('本溪市', '117000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('丹东市', '118000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('锦州市', '121000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('营口市', '115000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阜新市', '123000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('辽阳市', '111000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('盘锦市', '124000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('铁岭市', '112000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('朝阳市', '122000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('葫芦岛市', '125000', 6);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('长春市', '130000', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('吉林市', '132000', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('四平市', '136000', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('辽源市', '136200', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('通化市', '134000', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('白山市', '134300', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('松原市', '131100', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('白城市', '137000', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('延边朝鲜族自治州', '133000', 7);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('哈尔滨市', '150000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('齐齐哈尔市', '161000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鸡西市', '158100', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鹤岗市', '154100', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('双鸭山市', '155100', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('大庆市', '163000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('伊春市', '152300', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('佳木斯市', '154000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('七台河市', '154600', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('牡丹江市', '157000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黑河市', '164300', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('绥化市', '152000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('大兴安岭地区', '165000', 8);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('上海市', '200000', 9);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南京市', '210000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('无锡市', '214000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('徐州市', '221000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('常州市', '213000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('苏州市', '215000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南通市', '226000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('连云港市', '222000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('淮安市', '223200', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('盐城市', '224000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('扬州市', '225000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('镇江市', '212000', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('泰州市', '225300', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宿迁市', '223800', 10);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('杭州市', '310000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宁波市', '315000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('温州市', '325000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('嘉兴市', '314000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('湖州市', '313000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('绍兴市', '312000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('金华市', '321000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('衢州市', '324000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('舟山市', '316000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('台州市', '318000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('丽水市', '323000', 11);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('合肥市', '230000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('芜湖市', '241000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('蚌埠市', '233000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('淮南市', '232000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('马鞍山市', '243000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('淮北市', '235000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('铜陵市', '244000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('安庆市', '246000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黄山市', '242700', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('滁州市', '239000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阜阳市', '236100', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宿州市', '234100', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('六安市', '237000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('亳州市', '236800', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('池州市', '247100', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宣城市', '366000', 12);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('福州市', '350000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('厦门市', '361000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('莆田市', '351100', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('三明市', '365000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('泉州市', '362000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('漳州市', '363000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南平市', '353000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('龙岩市', '364000', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宁德市', '352100', 13);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南昌市', '330000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('景德镇市', '333000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('萍乡市', '337000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('九江市', '332000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('新余市', '338000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鹰潭市', '335000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('赣州市', '341000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('吉安市', '343000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宜春市', '336000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('抚州市', '332900', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('上饶市', '334000', 14);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('济南市', '250000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('青岛市', '266000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('淄博市', '255000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('枣庄市', '277100', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('东营市', '257000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('烟台市', '264000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('潍坊市', '261000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('济宁市', '272100', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('泰安市', '271000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('威海市', '265700', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('日照市', '276800', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('莱芜市', '271100', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('临沂市', '276000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('德州市', '253000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('聊城市', '252000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('滨州市', '256600', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('荷泽市', '255000', 15);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('郑州市', '450000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('开封市', '475000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('洛阳市', '471000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('平顶山市', '467000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('安阳市', '454900', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鹤壁市', '456600', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('新乡市', '453000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('焦作市', '454100', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('濮阳市', '457000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('许昌市', '461000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('漯河市', '462000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('三门峡市', '472000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南阳市', '473000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('商丘市', '476000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('信阳市', '464000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('周口市', '466000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('驻马店市', '463000', 16);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('武汉市', '430000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黄石市', '435000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('十堰市', '442000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宜昌市', '443000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('襄阳市', '441000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('鄂州市', '436000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('荆门市', '448000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('孝感市', '432100', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('荆州市', '434000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黄冈市', '438000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('咸宁市', '437000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('随州市', '441300', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('恩施土家族苗族自治州', '445000', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('神农架', '442400', 17);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('长沙市', '410000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('株洲市', '412000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('湘潭市', '411100', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('衡阳市', '421000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('邵阳市', '422000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('岳阳市', '414000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('常德市', '415000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('张家界市', '427000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('益阳市', '413000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('郴州市', '423000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('永州市', '425000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('怀化市', '418000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('娄底市', '417000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('湘西土家族苗族自治州', '416000', 18);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('广州市', '510000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('韶关市', '521000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('深圳市', '518000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('珠海市', '519000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('汕头市', '515000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('佛山市', '528000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('江门市', '529000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('湛江市', '524000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('茂名市', '525000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('肇庆市', '526000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('惠州市', '516000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('梅州市', '514000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('汕尾市', '516600', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('河源市', '517000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阳江市', '529500', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('清远市', '511500', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('东莞市', '511700', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('中山市', '528400', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('潮州市', '515600', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('揭阳市', '522000', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('云浮市', '527300', 19);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南宁市', '530000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('柳州市', '545000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('桂林市', '541000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('梧州市', '543000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('北海市', '536000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('防城港市', '538000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('钦州市', '535000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('贵港市', '537100', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('玉林市', '537000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('百色市', '533000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('贺州市', '542800', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('河池市', '547000', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('来宾市', '546100', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('崇左市', '532200', 20);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('海口市', '570000', 21);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('三沙市', '572000', 21);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('重庆市', '400000', 22);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('成都市', '610000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('自贡市', '643000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('攀枝花市', '617000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('泸州市', '646100', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('德阳市', '618000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('绵阳市', '621000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('广元市', '628000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('遂宁市', '629000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('内江市', '641000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('乐山市', '614000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('南充市', '637000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('眉山市', '612100', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宜宾市', '644000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('广安市', '638000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('达州市', '635000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('雅安市', '625000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('巴中市', '635500', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('资阳市', '641300', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阿坝藏族羌族自治州', '624600', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('甘孜藏族自治州', '626000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('凉山彝族自治州', '615000', 23);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('贵阳市', '55000', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('六盘水市', '553000', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('遵义市', '563000', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('安顺市', '561000', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('铜仁市', '554300', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黔西南布依族苗族自治州', '551500', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('毕节市', '551700', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黔东南苗族侗族自治州', '551500', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黔南布依族苗族自治州', '550100', 24);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('昆明市', '650000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('曲靖市', '655000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('玉溪市', '653100', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('保山市', '678000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('昭通市', '657000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('丽江市', '674100', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('普洱市', '665000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('临沧市', '677000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('楚雄彝族自治州', '675000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('红河哈尼族彝族自治州', '654400', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('文山壮族苗族自治州', '663000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('西双版纳傣族自治州', '666200', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('大理白族自治州', '671000', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('德宏傣族景颇族自治州', '678400', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('怒江傈僳族自治州', '671400', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('迪庆藏族自治州', '674400', 25);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('拉萨市', '850000', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('昌都地区', '854000', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('山南地区', '856000', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('日喀则地区', '857000', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('那曲地区', '852000', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阿里地区', '859100', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('林芝地区', '860100', 26);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('西安市', '710000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('铜川市', '727000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('宝鸡市', '721000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('咸阳市', '712000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('渭南市', '714000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('延安市', '716000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('汉中市', '723000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('榆林市', '719000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('安康市', '725000', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('商洛市', '711500', 27);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('兰州市', '730000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('嘉峪关市', '737100', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('白银市', '730900', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('天水市', '741000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('武威市', '733000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('张掖市', '734000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('平凉市', '744000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('酒泉市', '735000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('庆阳市', '744500', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('定西市', '743000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('陇南市', '742100', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('临夏回族自治州', '731100', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('甘南藏族自治州', '747000', 28);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('西宁市', '810000', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('海东地区', '810600', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('海北藏族自治州', '810300', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('黄南藏族自治州', '811300', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('海南藏族自治州', '813000', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('果洛藏族自治州', '814000', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('玉树藏族自治州', '815000', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('海西蒙古族藏族自治州', '817000', 29);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('银川市', '750000', 30);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('石嘴山市', '753000', 30);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('吴忠市', '751100', 30);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('固原市', '756000', 30);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('中卫市', '751700', 30);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('乌鲁木齐市', '830000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('克拉玛依市', '834000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('吐鲁番地区', '838000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('哈密地区', '839000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('昌吉回族自治州', '831100', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('博尔塔拉蒙古自治州', '833400', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('巴音郭楞蒙古自治州', '841000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阿克苏地区', '843000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('克孜勒苏柯尔克孜自治州', '835600', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('喀什地区', '844000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('和田地区', '848000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('伊犁哈萨克自治州', '833200', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('塔城地区', '834700', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阿勒泰地区', '836500', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('石河子市', '832000', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('阿拉尔市', '843300', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('图木舒克市', '843900', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('五家渠市', '831300', 31);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('香港特别行政区', '000000', 32);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('澳门特别行政区', '000000', 33);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('台湾省', '000000', 34);
INSERT INTO CITY( NAME, ZIPCODE,PROVINCEID)
VALUES ('三亚市', NULL, 21);

